// Components
import Header from "@components/ssr/header";
import Footer from "@components/ssr/footer";
// Libs
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// Styles
import "@styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | Create Next App",
    default: "Home",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
