// Components
import PostLink from "@components/client/postLink";
// Libs
import type { Metadata } from "next";
// Styles
import styles from "@styles/page.module.css";

export const metadata: Metadata = {
  title: "ISR",
  description: "Generated by create next app",
};

export default async function ISRPage() {
  return (
    <main className={styles.main}>
      <h1>ISR PAGE</h1>

      <div className={styles.grid}>
        <PostLink postId={1} />
        <PostLink postId={2} />
        <PostLink postId={3} />
      </div>
    </main>
  );
}
